# Generated by Django 4.0.2 on 2022-02-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
